# Generated by Django 5.0.4 on 2024-05-01 19:39

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Account Identifier')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Account Number')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Account Balance')),
            ],
        ),
    ]
