# Generated by Django 5.0.4 on 2024-05-08 03:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Account Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Account Number'),
        ),
    ]
