# Generated by Django 5.0.4 on 2024-05-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_balance_alter_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.account')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Account Points')),
            ],
            bases=('accounts.account',),
        ),
    ]
