name: Continuous Delivery

on:
  push:
    branches:
    - main
    - feature_*
  workflow_run:
    workflows:
      - "Continuous Integration"
    branches:
      - main
      - feature_*
    types: 
      - completed

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    #   name: Wait for tag to build
    # - uses: lewagon/wait-on-check-action@v1.3.4

    - name: Build docker image
      run: |
        docker build -t sysbanking:0.0 .

        