name: Continuous Delivery

on:
  push:
    branches:
    - main
    - feature_*
  workflow_run:
    workflows:
      - ci
    types:
      - completed

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Build docker image
      run: |
        docker build -t sysbanking:0.0 .

        