name: Package

on:
  push:
    tags:
    - rc-*

jobs:
  package-release-candidate:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    steps:
      - uses: actions/checkout@v4
      
      - name: Package source code
        run: |
          zip -r ${{ github.ref_name }}.zip .

      - name: Archieve source code package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}.zip
          path: ${{ github.ref_name }}.zip
