name: Package

on:
  push:
    tags:
    - rc-*
  workflow_run:
    workflows: [Continuous Integration]
    types:
      - completed

jobs:
  package-release-candidate:
    runs-on: ubuntu-latest

    if: |
      github.ref_type == 'tag'
      github.ref != 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Package source code
        run: |
          zip -r ${{ github.ref_name }}.zip .

      - name: Archieve source code package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}
          path: ${{ github.ref_name }}.zip
