name: Tag and Package

on:
  push:
    tags:
    - 'rc-*'
    branches:
    - main
    - feature*

jobs:
  tagging:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get current datetime
        run: echo "date=$(date +'%Y%m%d%H%M%S%N')" >> $GITHUB_ENV

      - name: Mount build tag name
        run: echo "TAG_NAME=build-${{ env.date }}" >> $GITHUB_ENV

      - name: Create build tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME
          
  packaging:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      
      - name: Create zip file
        run: |
          echo "RC_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "$RC_NAME"
          zip -r $RC_NAME.zip .

      - name: Archive file
        uses: actions/upload-artifact@v4
        with:
          name: $RC_NAME
          path: ./$RC_NAME.zip
