name: Tagging

on:
  push:
    branches:
    - main
    - feature*
  pull_request:
    branches:
    - main

jobs:
  tagging-commit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Mounting the Tag
        id: tagwriting
        run: echo "TAG_NAME=build-${{ env.date }}" >> $GITHUB_ENV

      - name: Tagging the commit
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME
