name: Tagging

on:
  push:
    branches:
    - main
    - feature*
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Mounting the Tag
        id: tagwriting
        run: echo $TAG_NAME
        env:
          TAG_NAME: build-${{ steps.date.outputs.date }}

      - name: Tagging the commit
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME
